// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ8_GgROcmmNN3drGKigd2AijQilUFVFY',
    appId: '1:818274996318:web:b82c1c025eae8161d6e4cf',
    messagingSenderId: '818274996318',
    projectId: 'e-commerce-749db',
    authDomain: 'e-commerce-749db.firebaseapp.com',
    storageBucket: 'e-commerce-749db.firebasestorage.app',
    measurementId: 'G-YJ6FM373YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWiK-xsGjVwEgkMD8Nhyh2N4UwfEoXLEc',
    appId: '1:818274996318:android:84b107cba8f22129d6e4cf',
    messagingSenderId: '818274996318',
    projectId: 'e-commerce-749db',
    storageBucket: 'e-commerce-749db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJY4LCyiaU_4ZO8kO0n-BjhPgJT08ocNs',
    appId: '1:818274996318:ios:9133d7ff0b9c43e6d6e4cf',
    messagingSenderId: '818274996318',
    projectId: 'e-commerce-749db',
    storageBucket: 'e-commerce-749db.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJY4LCyiaU_4ZO8kO0n-BjhPgJT08ocNs',
    appId: '1:818274996318:ios:9133d7ff0b9c43e6d6e4cf',
    messagingSenderId: '818274996318',
    projectId: 'e-commerce-749db',
    storageBucket: 'e-commerce-749db.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ8_GgROcmmNN3drGKigd2AijQilUFVFY',
    appId: '1:818274996318:web:af5ddedea429e806d6e4cf',
    messagingSenderId: '818274996318',
    projectId: 'e-commerce-749db',
    authDomain: 'e-commerce-749db.firebaseapp.com',
    storageBucket: 'e-commerce-749db.firebasestorage.app',
    measurementId: 'G-FNX62DV5VZ',
  );
}
